### ISSUE TITLE
タグTLのunlisted投稿がAPI経由で外から閲覧できる

### ISSUE THREAD

**Issue by fvh-P** [imas/mastodon#123]
`GET /api/v1/timelines/tag/:hashtag`
がアクセストークン不要になっているため、任意のタグ付きunlisted投稿が外からトークンなしで見れるようになってしまっています。

「タグ付きunlistedのタグTLへの掲載は`ネタバレ防止・会話の分離`が目的」
「そもそも個別のアカウントページに行けばだれでも見られる」
なのでこのままでいいという考えもできます。

**アイマストドンでのhashtagタイムラインの扱い**がまだ曖昧な印象があるので、そこ含めて検討が必要かと思います。

個人的には**トークンなしのアクセスのときunlistedは掲載しない**という対応が妥当なのかなと思います。（そのような動作ができるかは未検討です。。。）

**Comment by deflis** [comment]
トレンドタグUIでもリンクを張っていますが、ログインしない状態でもすでにハッシュタグTLが見れるUIがあります。
https://deflis.github.io/imastodon-trendtag/
https://imastodon.net/tags/imas_dj
変えるならここの仕様も変える必要が有るかなと思います。

**Comment by takayamaki** [comment]
ふぁぼ原くんの言う通りtokenがある場合はunlistedを含め、ない場合はunlistedを含めないという動作が妥当かなと思います。

タグTLについてはREDIS pub/subの段階で`timeline:hashtag:${req.query.tag.toLowerCase()}:local:authorized` および
 `timeline:hashtag:${req.query.tag.toLowerCase()}:authorized` といったようなキーのpub/subチャネルを作り、`streaming/index.js` で同じエンドポイントで受けて内部でsubsclibeするチャネルを切りかえるような実装が比較的簡単そうかなと思います。

**Comment by takayamaki** [comment]
こちらマージ&デプロイ済みなので閉じますー
