### ISSUE TITLE
Announcements component has some warning on React

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#13]
![image](https://user-images.githubusercontent.com/24884114/27015596-aca7fe00-4f4c-11e7-8604-b3aae086c2fd.png)

**Comment by fvh-P** [comment]
I also found these warnings at https://imastodon.net; however, I suppose these warnings will disappear after update to v1.4.
Actually, these have already disappeared in my own deployment on heroku. (The deployed branch is even with imas/imastodon.)

**Comment by takayamaki** [comment]
I have got same warning from v1.4.1(commit ba08bd05678664bc24e5d315f72d765f0c8abca5).
![image](https://user-images.githubusercontent.com/24884114/27061841-026b2058-5022-11e7-84f8-47feaba91813.png)

and I have got it at v1.4.2 on my local branch too.

This seems to be a warning that depends only on Announcements component.

**Comment by fvh-P** [comment]
Hmm... I retried deploying several times, still I can not see it in my environment. Aren't the warnings only seen in the "development" environment?

Aside from that, I modified the code according to the warnings (commit [```3fa862e```](https://github.com/fvh-P/mastodon/commit/3fa862e1b2abe1f7d8da609a182b73fd5627edc8) in my repository). I do not know whether it is a correct change, but I think the warnings suggest to make such a change.

**Comment by lnanase** [comment]
In order to check these React warnings, it is necessary to change the setting on Heroku.

1. Heroku "NODE_ENV" settings change "development".
`$ heroku config:set NODE_ENV=development`

1. This commit apply.
https://github.com/lnanase/mastodon/commit/0e66643cc26a54dcc13c859098ad4680b670c6b4

1. Deploy Heroku.

Thank you.

**Comment by takayamaki** [comment]
#17 で解消されたのでcloseします
