### ISSUE TITLE
管理者メッセージ欄の要否

### ISSUE THREAD

**Issue by lnanase** [imas/mastodon#143]
@takayamaki 
#8 で管理者メッセージ機能を追加しましたが、
その後、 #131 でお知らせ機能の動的化を達成しました。

今後、お知らせ機能を使用するため、管理者メッセージ欄は不要となりますか？
不要の場合は削除するPRを作ろうと思いますので、
お手すきの際にご回答お願い致します。

**Comment by takayamaki** [comment]
そうですね、不要となりました。
暇を見て自分で消そうと思っていましたがやっていただけるのであればお願いします 🙏
