### ISSUE TITLE
一部背景画像がアイマストドン仕様から元に戻ってしまった

### ISSUE THREAD

**Issue by fvh-P** [imas/mastodon#153]
![don](https://user-images.githubusercontent.com/8458066/37352641-12af8d88-2721-11e8-99e9-2dd826c0c6df.PNG)

前バージョンまではアイマストドン仕様（矢印）になっていたはずです。
#150 で取り込まれた[**これ**](https://github.com/imas/mastodon/blob/imastodon/app/javascript/images/elephant_ui_plane.svg)が原因？

**Comment by lnanase** [comment]
v1.3.1マージの時にやっときます:sushi:

**Comment by lnanase** [comment]
https://imastodon.net/share

この画面は手付かずだったようです
