### ISSUE TITLE
まれにトレンドタグの順位が正しくない

### ISSUE THREAD

**Issue by fvh-P** [imas/mastodon#165]
Sometimes the order of the trend tags is incorrect.
Immutable.fromJS() does **not** seem to preserve the order of the passed JSON. I guess it causes this problem.

#154 と#158 でトレンドタグの保存にソート済みセット型を使い始めてから、トレンドタグの順位が正しくない不具合がまれに発生します。
ChromeのJSコンソールを使用して検証したところ、Immutable.fromJS()が**渡されたJSONの順番を保持していない**ように見えるので、それが原因ではないかと推測しています。

スクリーンショットなどを撮り忘れたので引き続き調査します。

**Comment by fvh-P** [comment]
うーん…なんででしょう…
![7 _li](https://user-images.githubusercontent.com/8458066/40618369-4613572c-62cc-11e8-8310-c97b7fc6cda8.jpg)

**Comment by deflis** [comment]
Mapだと順番が保証されないのかも。保証したいならOrderedSetに変換するしかなさそうな。
