### ISSUE TITLE
メニューとカラムでキーボードショートカットのアイコンが異なる

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#170]
キーボードショートカットヘルプについて、アイコンがimastodon-faqと被ってしまうためメニュー内は #137 で変更していましたが、 https://github.com/imas/mastodon/blob/imastodon/app/javascript/mastodon/features/keyboard_shortcuts/index.js#L24 を変更し忘れていました

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lnanase** [comment]
#169 のPRでは対応させています。

**Comment by lnanase** [comment]
#169 で対応致します。
