### ISSUE TITLE
本家v2.4.1rcで追加されたTrending hashtags機能への対応

### ISSUE THREAD

**Issue by fvh-P** [imas/mastodon#171]
tootsuite/mastodon#7638 でTrending hashtagsという機能が追加されました。
こちらの独自機能と被る機能なので何らかの対応が必要ではないかと思います。

考えられる対応策としては
+ 独自機能を消して本家の機能に合わせる
+ 本家の機能は取り込まずに独自機能を維持する
+ (両方取り込む)

ですが、それ以外にもAPIエンドポイントをどうするか (本家に合わせるかどうか) や、本家の機能で追加されたUIを利用できないかなど検討すべき点はあるかと思いますのでIssueを建てておきます。

**Comment by takayamaki** [comment]
本家で入ったTrending hashtagsはアイマストドンの機能要件には沿っていませんが、
わざわざ削除するのも不要なコード差分を作って追従が面倒くさくなるだけなので両方取り込むでよいと思います。

マルチカラム状態だと本家のTrending hashtagsはどうせほぼ見る機会ないですし…

**Comment by rinsuki** [comment]
https://github.com/tootsuite/mastodon/pull/7711 によって本家からトレンド機能が削除されたようです

**Comment by fvh-P** [comment]
削除のPRと関連するIssueを読んできました。あの様子だとしばらくは復活しなさそうですね。
ただ、向こうのUI案は何かうまく使えそうなのでちょっと検討してみます (グラフが表示されるのでうまく使えばどのくらい盛り上がっているかがわかりやすくなりそう)

issueはとりあえずcloseします
