### ISSUE TITLE
テーマをMastodon(ライト)もしくはハイコントラストに設定すると、アイマストドン独自機能のスタイルが適用されない

### ISSUE THREAD

**Issue by lonsagisawa** [imas/mastodon#172]
![ss20180620_215](https://user-images.githubusercontent.com/5173607/41647495-863c2d46-74b1-11e8-9c66-f6877a329a98.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by lonsagisawa** [comment]
![ss20180620_216](https://user-images.githubusercontent.com/5173607/41648198-368b9e1a-74b3-11e8-87dc-bf5c774268e7.png)

公開範囲が未収載・フォロワー限定になっているトゥートのユーザーアイコンが出なくなります。

**Comment by takayamaki** [comment]
これの存在をすっかり忘れてました
直します

**Comment by takayamaki** [comment]
アイマストドン独自部分が含まれていなかったのが原因なので https://github.com/imas/mastodon/pull/176 としてとりあえず表示できる程度には直る予定です

**Comment by lonsagisawa** [comment]
![2018-08-21 23 31 19](https://user-images.githubusercontent.com/5173607/44407985-5edeb380-a59a-11e8-974a-af83a2900b1b.png)

報告が遅くなってしまい申し訳ございません。2018-08-21現在でとりあえず表示はできる程度の修正は確認しましたが、お知らせの文字が薄くて見づらくなっています。

**Comment by lonsagisawa** [comment]
It's abandoned, and even not an issue since ANYONE do NOT use light theme.
