### ISSUE TITLE
モバイル環境から閲覧時の検索カラム位置について

### ISSUE THREAD

**Issue by qunaud** [imas/mastodon#175]
モバイル環境から閲覧した際に検索カラムが真ん中にあり、
スワイプですばやく通知やHTLに移れない状態です
検索の使用率は低いと思われますので左端に移動できないでしょうか？

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
![f0644452d64d0b15](https://user-images.githubusercontent.com/13547972/41765875-5400cbda-7640-11e8-9bc1-8049ae9ef9e2.jpeg)

**Comment by fvh-P** [comment]
本家で変えてくれるなら変えてもらおうということで tootsuite/mastodon#7877 にプルリクを出しました。
ダメって言われたら独自で変えましょう。

**Comment by takayamaki** [comment]
tootsuite/mastodon#7877 がマージされたのでgargron先生の次回作(2.4.3)にご期待ください(?)

**Comment by fvh-P** [comment]
imastodonでもバージョンアップが行われて変更が適用されたので閉じますー
