### ISSUE TITLE
SafariでPinned Tab Iconsが正しく表示されない

### ISSUE THREAD

**Issue by hacusk** [imas/mastodon#182]
https://imastodon.net/@hacusk/100586763790959359

mask-icon.svgが黒と透明な背景のみで構成されなければならないところが、フルグラフィックな画像になっていることが原因と思われます。

**Comment by lnanase** [comment]
申し訳ありません。
上記のスクショがどこの画面の部分なのかがわからないので、
画面名もしくはURLか表示される操作をご教示頂けますでしょうか...

**Comment by hacusk** [comment]
こちらのスクショはmacOS版のSafariで https://imastodon.net/web/getting-started をタブ固定した状態のウィンドウ上部のになります。
一番左にある四角いタブがimastodonのタブになります。

本来であれば下記のスクショのTwitterやFacebookのようにロゴがでます。
https://imastodon.net/@hacusk/100588554613509746

参考までにAppleのリファレンスは以下のものになります。
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

**Comment by fvh-P** [comment]
https://github.com/imas/mastodon/blob/imastodon/public/mask-icon.svg
画像はこいつで

https://github.com/imas/mastodon/blob/dbb88991c4868659767bbc23a2ab19d49654b618/app/views/layouts/application.html.haml#L8
タグはここですかね

https://github.com/tootsuite/mastodon/pull/1585 これも参考になりそうです

**Comment by lnanase** [comment]
詳細なご説明有難うございます。
勉強になりました。

仮に私が対応するとなるとメインPCがWindowsなため、
対応が遅くなることご理解頂けると助かります :bowing_man:
