### ISSUE TITLE
フィルター機能の「日本語(im@s)」での訳語がズレている

### ISSUE THREAD

**Issue by gomao9** [imas/mastodon#185]
表題の通り、フィルター機能で「日本語(im@s)」の訳語がズレています。
現行の実装は下記の画像を参照ください。

**日本語**
![image](https://user-images.githubusercontent.com/559370/44538663-fe3bac00-a73c-11e8-979e-280d65648058.png)

**日本語(im@s)**
![image](https://user-images.githubusercontent.com/559370/44538703-1c091100-a73d-11e8-88c8-3311de194256.png)

正しい訳語は下表の通りと考えます。

| 日本語             | 日本語(im@s)(誤)  | 日本語(im@s)(正)                                   |
| ------------------ |-------------------|----------------------------------------------------|
| ホームタイムライン | 楽屋              | オフィス                                           |
| 公開タイムライン   | ライブステージ    | (public timeline に相当するim@s語ありましたっけ……) |

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fvh-P** [comment]
ホームタイムライン -> オフィス
通知 -> ホワイトボード
公開タイムライン -> ???

ここでいう「公開タイムライン(public)」とは「community, account, hashtag」の総称なんでしょうかね？
https://github.com/imas/mastodon/blob/20fefdb7145b48449e9d6a824a9846dadfd6ac2f/app/javascript/mastodon/selectors/index.js#L22-L36

@takayamaki, @lnanase
