### ISSUE TITLE
Android/iOSで撮影したスクリーンショットがpng形式なので画像サイズが嵩む

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#19]
アイマストドンの画像投稿の利用傾向として、デレステ/ミリシタを始めとしたスクリーンショットの投稿が多いです。

Android/iOSでスクリーンショットを撮影するとpng形式で保存されるため、アイマストドンへ投稿された際に再圧縮を経てもファイルサイズが1MBを超える場合ほとんどです。

s3に蓄積されるメディアファイルは参照される可能性がある以上削除することは出来ないため、データ転送量とストレージ料金の観点からpng形式が不得意な傾向の画像をjpg形式に変換して保存する必要があります。

**Comment by takayamaki** [comment]
今のところ、
- png
```
if( 透過png )
  png形式で保存
else
  jpgに変換してみる
  if( jpgのファイルサイズ<pngのファイルサイズ )
    jpgで保存、pngのほうは消す
  else
    pngで保存、jpgのほうは消す
  end
end
```
くらいの処理をすればいいのかなと思ってます

**Comment by lnanase** [comment]
imagemagickではjpg変換のときに容量上限を指定するオプションが存在します。
http://www.imagemagick.org/script/command-line-options.php#define

jpg変換の時もその辺りを使ったほうが良さそうですね。

**Comment by takayamaki** [comment]
`-define jpeg:extent=1MB` くらいですかねぇ。

slackにも書きましたが、pngを問答無用でjpgに変換するだけならそれほど苦労せずにできそうなんですけれど、
元が透過pngだった場合にjpgにしてしまうと透過だった部分が真っ黒になってしまうので、
アルファチャネルが存在して、かつアルファチャネルの最小値が255未満(つまり透過部分が存在する)場合にはpngのままにしたいのですよね…

で、そこの判定をするにはどうすればいいのか、そもそもpaperclipで出来るのかどうかの調査で今詰まってます

**Comment by takayamaki** [comment]
希望する動作は #23 で概ね実現出来たので、あとは-define jpeg:extent=1MBを入れるか入れないかと、
rspecのテストケースの追加ですね

**Comment by takayamaki** [comment]
422バグも解消されたので閉じます
