### ISSUE TITLE
タイムライン上の画像を常にNSFW扱いにするオプションが欲しい

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#190]
機能内容的には本家案件ですが要望が上がってきたのでメモ。

現在マストドンには「閲覧注意としてマークされたメディアも常に表示する」というオプションはありますが、「どのメディアも常に閲覧注意として扱う」オプションはありません。

そのためNSFWとしたほうがよいと考えられる画像にNSFWを付けないで/つけ忘れて投稿する人がいた場合に自衛する手段がありません。

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by takayamaki** [comment]
- そのまま
- 常にNSFWとして扱う
- 常に表示する

の三値になるので設定のUIがたぶんリストボックスになる

**Comment by fvh-P** [comment]
https://github.com/tootsuite/mastodon/pull/8569 
ささっと作れたので本家に投げました

**Comment by takayamaki** [comment]
本家v2.6.5追従して tootsuite/mastodon#8569 も入ったのでcloseします
