### ISSUE TITLE
特定のアカウントにおいて、LTLの大規模な取得漏れが発生する

### ISSUE THREAD

**Issue by lonsagisawa** [imas/mastodon#202]
ある方が報告していた大規模なLTLの取得漏れですが、私のアカウントでも発生しました。

* LTLには画像付きのトゥート・ハッシュタグのついたトゥートだけが流れてきます。
* 他の人からは私が公開でしたトゥートは見えているようです。
* HTLは正常に使うことができます。
* WebUIに限らず、他のクライアントでも発生します。
* 取得漏れが発生するようになる前に行った操作は「NSFW付きの画像をデフォルトで表示するかどうか」のチェックの解除です。この設定は自分で有効にした覚えがないのに有効になっていました。

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by takayamaki** [comment]
- 発生した時刻を概ねでよいので教えてください
- 当該現象の発生時、開発者コンソールのJavascriptコンソールに何らかのエラー表示はありましたか
- REST APIでの取得(F5などでの再読み込み)で改善されましたか

**Comment by lonsagisawa** [comment]
* 11月24日の14時頃からです。
* 現在も当該の現象が発生し続けており、コンソールには以下のエラーが出ています。
![image](https://user-images.githubusercontent.com/5173607/48977253-5c7c8000-f0da-11e8-9d3b-1b084db917fd.png)
* REST APIでの取得でも改善されません。

**Comment by takayamaki** [comment]
DB上のデータを調べたところ、「イタリア語であると自動判定された投稿のみを表示する」という設定になっているようです。
https://imastodon.net/settings/preferences から、下記チェックボックスに誤ってチェックが入ってしまっていないかを見てみてください。

![image](https://user-images.githubusercontent.com/24884114/48978836-5d6edb00-f0f5-11e8-94fa-d38b456c2866.png)

**Comment by lonsagisawa** [comment]
Worked like a charm.

(こんな設定した覚えがないのですが、これはこの問題とは関係ないのでcloseします)

**Comment by takayamaki** [comment]
ラベル要素の幅が広すぎて誤クリックが発生したと思われるので、CSS変えるプルリクを出しておきました
https://github.com/tootsuite/mastodon/pull/9348
