### ISSUE TITLE
タグロック中に1度投稿するとカーソル位置がタグの後ろに行ってしまう

### ISSUE THREAD

**Issue by fvh-P** [imas/mastodon#208]
(おそらく) 本日のアップデート以降、タグロック中の投稿後、カーソル位置がハッシュタグの後ろに行ってしまいます。

カーソル位置を | で示すと、
従来は
「| #hogehoge」
だったのが、今は
「#hogehoge|」
になってしまいます。

**Comment by lnanase** [comment]
えーpriority highなのーｗ

**Comment by takayamaki** [comment]
いやー、緊急で対応しなきゃいけないほどじゃないからmiddleくらいかなぁ

不便なのはわかる

**Comment by takayamaki** [comment]
が、優先度高い別の個人タスクが後ろに詰まってるのでちょっとすぐにはむり
