### ISSUE TITLE
imastodon.netを利用しようとするとSafariの入力がもっさりする

### ISSUE THREAD

**Issue by mikage-961pro** [imas/mastodon#234]
> **【2019/11/27更新】**
>Safari 13シリーズが入ったmacOS Mojave 10.14の複数台のMacで初期環境で確認をしましたが同現象でした。本件は**Appleのエンジニアと確認中**です。

### Expected behaviour
imastodon.netを利用しようとするとSafariの入力がもっさりする。

[issue_Movie.zip](https://github.com/imas/mastodon/files/3884382/issue_Movie.zip)

### Steps to reproduce the problem

1. imastodon.netを開く
2. 投稿しようとすると入力がもっさりしてしまう。

### Specifications
現状、imastodon.blueとtwitterでは問題ない状況。
他のドンでも検証はしてみるが他では現状見られていないため、Safariとimastodon.net方で何かあるのかと推測する。

### 影響範囲
Browser Version：**Safari13.0-13.0.3 (14608.3.10.10.1)**
OS version：**10.14.6（18G1012）**

**Comment by acid-chicken** [comment]
Memo: I found the following environment (my Mac) is not affected.

<dl><dt>macOS</dt><dd>10.15 Beta (19A546d)</dd></dl>
<dl><dt>Safari</dt><dd>13.0 (15608.2.5)</dd></dl>
<dl><dt>Safari Technology Preview</dt><dd>Release 96 (Safari 13.1, WebKit 15609.1.9.7)</dd></dl>

**Comment by mikage-961pro** [comment]
> Memo: I found the following environment (my Mac) is not affected.
> 
> macOS
> 10.15 Beta (19A546d)
> Safari
> 13.0 (15608.2.5)
> Safari Technology Preview
> Release 96 (Safari 13.1, WebKit 15609.1.9.7)

Safari issue for Mac OS 10.14 Mojave.

**Comment by mikage-961pro** [comment]
<img width="1440" alt="スクリーンショット 2019-11-26 21 31 14" src="https://user-images.githubusercontent.com/50665049/69633742-27f82700-1094-11ea-85da-9ee2966ccce3.png">

**Comment by rinsuki** [comment]
再現できたかも?な環境
- Mac mini (late 2014)
- macOS 10.14.6 (18G95)
- Safari 13.0.3
- macOS default IME

AquaSKKでは再現できませんでした。

**Comment by rinsuki** [comment]
ただしこの環境はHDDへのキャッシュなしアクセスが鬼重いのでその影響もあるかも。

**Comment by mikage-961pro** [comment]
【2019/11/27 Update】
問題が起きている検証端末でMacOS10.15 Catalinaにアップデートしたら問題解決するため、おそらくMojaveのSafariなどに問題があるのかと思われる

**Comment by mikage-961pro** [comment]
**＊＊本現象に関してエンジニア確認となりました。＊＊**

> ＋**MacOS 10.14までで本問題が発生してしまう場合のトラブルシューティング**
> [MacOSの復元機能](https://support.apple.com/ja-jp/HT204904)で10.14.6を上書きインストールを実施してください。Safari 12にダウングレードできます。

**Comment by mikage-961pro** [comment]
エンジニアに確認したところ、MacOS 10.14でimastodon.netを利用する場合、他社のGoogle Chromeなどを利用するかSafari 12を利用するようにとこと。
しかし、imastodon.blueでは問題発生しないのであれば、サイト側の問題であろうとことです。
