### ISSUE TITLE
「追加のハッシュタグ」がストリーミングで流れてこない

### ISSUE THREAD

**Issue by yakitama** [imas/mastodon#240]
Web UI にピン留めしたハッシュタグカラムに「追加のハッシュタグを含める」で複数のハッシュタグに関するトゥートを表示できるカラムを作成した場合に、追加のハッシュタグを含むトゥートについてストリーミングで流れてきません。
imastodon.net および imastodon.blue (imastodon-20200328 (based on v2.8.4) に未収載が流れてこない不具合修正だけ適用したもの)、の両方で再現しています。

再現手順です。
1. ハッシュタグカラムをピン留めします（ここでは「imas」というハッシュタグカラムをピン留めしたものとします）。
2. カラムの設定を開き、「このカラムに追加のタグを含める」スイッチを ON にします。
3. 「いずれかを含む」欄に「徳川まつり」を入力します。
4. カラムがリロードされると、カラムには imas と 徳川まつり のハッシュタグを含むトゥートが掲載されます。
5. そのままで、新たに 徳川まつり のハッシュタグを含むトゥートを、公開/未収載 を問わず投稿します。

このとき、期待する結果としては『新たに投稿した「徳川まつり」のハッシュタグを含むトゥートがカラムに掲載される』ですが、実際の挙動は『掲載されない』です。

Web UI とサードパーティクライアント（Subway Tooter）で挙動が違うように見えるのと、まだ自分で mastodon のコードを読み込んでいないので、イマイチ原因までは分かりません。ご協力いただければ幸いです。

**Comment by rinsuki** [comment]
WebUIからStreaming APIに接続する際に、一つめのタグでしかWebSocketに繋いでいないように見えます。恐らくマージミス? (さすがに本家バグだったらもっと早く気づかれてる気がする)
![image](https://user-images.githubusercontent.com/6533808/80433753-bd912e80-8932-11ea-8adf-e7a2d4188e10.png)

**Comment by rinsuki** [comment]
ちなみに: バニラv3.1.3ではこうなる (正しい挙動)
![image](https://user-images.githubusercontent.com/6533808/80434020-9555ff80-8933-11ea-8d0c-18f7eefd520d.png)

**Comment by rinsuki** [comment]
https://github.com/imas/mastodon/blob/13ad796a840971cf7cba8d799696e1429df483cc/app/javascript/mastodon/features/hashtag_timeline/index.js#L83-L107

ここの最初の行でisLocalを足したのに、最後の行でisLocalを渡してないせいだ!!!

**Comment by yakitama** [comment]
rinsuki さんに作成いただいた PR コミットを一足先に blue/mastodon に取り込ませていただいて、本日から動き始めました。いい感じに動いています。ありがとうございました。
