### ISSUE TITLE
pngファイルが正常なものと判定されない?

### ISSUE THREAD

**Issue by maraigue** [imas/mastodon#25]
https://imastodon.net/@dousenP として利用させていただいている者です。

https://hhiro.net/tmp/data/1500861571_20170724-AJURIKA.png
このpngファイルをトゥートに入れるためにアップロードしようとすると、エラーメッセージが出て失敗します。
エラーメッセージ: `422 バリデーションに失敗しました: FilePaperclip::Errors::NotIdentifiedByImageMagickError, FilePaperclip::Errors::NotIdentifiedByImageMagickError`
他のインスタンスでは問題なくアップロードできるので、このインスタンスにおける画像アップロードの取り扱いを変更した箇所によるものと思われます。
以上お知らせします。

**Comment by takayamaki** [comment]
ご報告ありがとうございます。

こちらの問題については実は既知でして、アップロードされたオリジナルのpng画像が16KB未満だった場合に失敗するのではないか、という仮説までは立っているのですがそれ以上の詳細な挙動ならびに原因の特定には至っていない、という状況です。

ご不便をおかけしますが、同じ画像をgifかjpgで保存したものですと問題なくアップロードできますので、異なる形式での投稿が可能でしたら取り急ぎそちらで回避いただければと思います。

**Comment by fvh-P** [comment]
私も独自に調査を行ったのですが、ペイントブラシで適当に作った以下のPNG画像(約40KB)がアップロードできませんでした。

![test](https://user-images.githubusercontent.com/8458066/28510207-eba726f2-7081-11e7-83a3-518cccd3aa2d.png)

その他アップロードを試行して失敗したPNG画像をピックアップして、ローカル環境にてImageMagickを用いてJPGに変換したところ、今のところ全ての画像でファイルサイズが
JPG > PNG
となっています。

そうなる場合はサイズの小さいPNGで保存するのが期待の動作ですが、期待通りに動作していないのではないかと考えられます。

そうするとやはり怪しいのは[この辺](https://github.com/imas/mastodon/blob/imastodon/lib/paperclip/img_converter.rb#L20-L27)でしょうか。

**Comment by deflis** [comment]
最後 `return tmp_file` がいるのでは？？？？

**Comment by lnanase** [comment]
> return tmp_file

rubyではメソッドのreturnは省略可能で、その場合は
最後の式を評価した値 (この場合 tmp_file) がそのまま戻り値になります。

**Comment by rinsuki** [comment]
とりあえず、例外飛んだらpngで保存するようにすれば「上げられない」現象は回避できませんかね...?

**Comment by gomao9** [comment]
> とりあえず、例外飛んだらpngで保存するようにすれば「上げられない」現象は回避できませんかね...?

ファイルタイプが判別できないという意味のエラーが出てるので、問題のpngをアップロードした場合と、本当に画像以外のファイルがアップロードされた場合との区別ができないんではないかと思いますが、いかがでしょう。

**Comment by rinsuki** [comment]
![image](https://user-images.githubusercontent.com/6533808/28774098-04634dba-7627-11e7-88bc-1f124d9018c3.png)
とりあえず適当なテキストファイルを上げてみましたが、画像ではない場合はおそらく上のエラーでpng->jpg変換処理より前で弾かれるので、大丈夫だと思います

**Comment by gomao9** [comment]
@Petitsurume 
検証ありがとうございます。
であれば対症療法としては良さそう？

**Comment by fvh-P** [comment]
問題のpngをアップロードしようとしたときに、どこから例外が投げつけられているのかいまいちよくわからないのですがどなたか分かります？
ログを見ると
`identify -format '%wx%h,%[exif:orientation]' 'ファイル名.png[0]'`
を実行した直後に
`Paperclip::Errors::NotIdentifiedByImageMagickError`が出てますが、私が変更した箇所にはこの形のidentifyコマンドを実行するようなコードはないはずなので…

**Comment by takayamaki** [comment]
![01dccb6ff974a4bd](https://user-images.githubusercontent.com/24884114/28803746-c4753a88-7699-11e7-96fa-e2df24679c26.png)
![ac5e6db329a7454a](https://user-images.githubusercontent.com/24884114/28803752-c9be5218-7699-11e7-9837-a8d981e67da5.png)
より、明示的に書いてなくても色々な段階でidentify通ってるようです。
その中の最後の保存する段階でidentifyから結果が取れなくて例外投げられている、というところまでは読めているのですが…
具体的にどのような値がidentifyから帰ってきてその結果取れなかったのかがまだ出せてないです

**Comment by fvh-P** [comment]
なんかとてつもなく腑に落ちない感じですけど一応治りました…
素通しするときは`tmp_file << file.read`が許されて一度変換して比較した後は許されないのか…？

**Comment by deflis** [comment]
ああ、なんとなく原因わかりました。
ファイルに対する File#read はポインタを保持してるので、変換したときにはポインタがすでにEOFに行ってしまっているのでは…。

**Comment by fvh-P** [comment]
試しに[このように](https://github.com/fvh-P/mastodon/blob/4218a679fc07c2cf2ea72553bc82f47a6ec58c14/lib/paperclip/img_converter.rb#L26-L26)
`file.rewind`
`tmp_file << file.read`
としてreadの前にファイルポインタを先頭に戻すようにしましたがやはりバリデーションエラーとなりますね。

**Comment by lnanase** [comment]
自分なりにチェックしてみました。
ご確認お願い致します。
https://github.com/imas/mastodon/pull/27#issuecomment-319588866

**Comment by deflis** [comment]
そもそも、インスタンス変数の `@file` をそのまま返す実装でも問題ないようです。
https://github.com/deflis/mastodon/commit/faed8d523706b3fa3bfdbda78ef2c2882b16bb47

githubで幾つかPaperclipのProcessorのソースを見ましたが、この実装が幾つかありました
ex: https://github.com/janko-m/paperclip-dropbox/blob/be13e6c1fda5507e17df425b5ac3cba5d472ab87/spec/support/paperclip.rb#L13

あと、さっき別のソースで見つけたのですが、rewindしなきゃいけなかったのは出力先のファイルの方もだったようですね…。
ex: https://github.com/puneetimpinge/get3questions/blob/d4f77c2cc15813f28703449b9500f1fcf18571f0/lib/paperclip_processors/watermark.rb#L52-L66
