### ISSUE TITLE
実況をするとLTLを占領してしまう問題をどうにかする

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#29]
現状のアイマストドンでは、ハッシュタグ付きのtootを未収載で行ってもタグカラムに表示されないので、「LTLは占領したくないけど実況はしたい」というニーズに対応できていません。

下記を実装することで、
 - 実況したい人
   - タグをいちいち手入力しなくてもタグ入りで連投できるようになる
   - 上記タグ自動入力機能の連動で未収載にできるようになる
     - タグを宣伝したいときには手動で公開範囲を設定すればよい
   - タグを追いたいときはタグカラムを開けば追える(しかもお気に入りタグ機能から簡単に開ける
 - 実況以外の話がしたい人
   - 流速の早いタグの大半が未収載になるのでLTLが占領されなくなる
 
というような棲み分けならびにアイマストドンの緩やかな規模の拡張ができるのではないかと思います。

- [x] 未収載タグ付きのtootがapi/v1/streaming/hashtagに出るようにする
- [x] friends.nicoからお気に入りタグ機能を拝借する
  - [x] お気に入りタグ機能の自動入力連動で公開範囲をセットするようにする

**Comment by takayamaki** [comment]
related #28

**Comment by fvh-P** [comment]
> 未収載タグ付きのtootがapi/v1/streaming/hashtagに出るようにする

今のところ、api/v1/timelines/tagには未収載のものも反映されるようにできましたが、streamingには反映されません。streamingのデータを生成する際にどこでVisibilityのフィルタリングをしているのかがわからないので行き詰っています。

timelines/tagの方に反映させるために行った変更は[ここ](https://github.com/fvh-P/mastodon/commit/935f231a21ba8575c416f8a4140ca44eeed94655)をご覧ください。

**Comment by deflis** [comment]
@fvh-P 調べたところ、JavaScript側で送ってないのはわかったので、Sidekiq側のコードを調べました。

ハッシュタグを送ってるのはここで
https://github.com/imas/mastodon/blob/imastodon/app/services/fan_out_on_write_service.rb#L61-L68
呼び出す前にフィルタリングしてるようです。
https://github.com/imas/mastodon/blob/imastodon/app/services/fan_out_on_write_service.rb#L22

あと削除周りで
ここや
https://github.com/imas/mastodon/blob/imastodon/app/services/batched_remove_status_service.rb#L71-L74
ここでも
https://github.com/imas/mastodon/blob/imastodon/app/services/remove_status_service.rb#L70-L75
ハッシュタグのストリーミングが送られているようです。

**Comment by takayamaki** [comment]
ストリーミング周りは基本的に
1. Puma上で動作するRailsがユーザからの操作(post、delete、fav等)を受ける
1. sidekiqにジョブを積む
1. sidekiqジョブが対応するRedisのpub/subチャンネルにメッセージをpublish
1. pub/subチャンネルをsubscribeしていたnode.jsがメッセージを受けてWebsocket経由でクライアントに配信

という流れで動いていて、`/api/v1/streaming/hashtag`および`/api/v1/streaming/hashtag:local`に流れてくるのがpostとdeleteだけなら上記猫ロキさんが挙げてる部分の`redis.publish("timeline:hashtag:#{hashtag}:local", payload)`の実行条件を書き換えれば出来るはず

/api/v1/streaming/hashtagや/api/v1/streaming/hashtag:localが認証を受けてなくても見れるのかどうかをちゃんと調べる必要がありますが…

**Comment by fvh-P** [comment]
@deflis さんの調査をもとに条件の変更を行い、`/api/v1/streaming/hashtag`および`/api/v1/streaming/hashtag/local`においてunlistedなハッシュタグ付きトゥートも流れてくるようになりました。deleteイベントもちゃんと流れてきます。
一応画像を貼っておきます
![2017-08-05_li](https://user-images.githubusercontent.com/8458066/28996248-24512a5c-7a37-11e7-8384-9873193a0359.jpg)

変更コミットは[こちら](https://github.com/fvh-P/mastodon/commit/2edbbdbd99f9b0047cd7839e2189d40fcf05e8b1)です。streamingのために行った変更は条件式1つの追加だけですので、他にも必要な変更があるかもしれません。

**Comment by takayamaki** [comment]
Chromeのコンソールから見た感じ/api/v1/streaming/hashtagでも/api/v1/streaming/hashtag:localでもアクセストークン渡してるので無認証では取れなさそうだけど、
Web画面から見れるのは/api/v1/streaming/hashtagのみで/api/v1/streaming/hashtag:localに切り替えることはできないようで。

まあこれの切り替えの実装はまた別の機能ですねー

**Comment by fvh-P** [comment]
`/api/v1/streaming/hashtag/local?tag=&access_token=`
Web画面でも見れません？

**Comment by takayamaki** [comment]
websocket経由では取れるけど、Web画面(React)では [javascript/mastodon/stream.js](https://github.com/imas/mastodon/blob/imastodon/app/javascript/mastodon/stream.js)と[javascript/mastodon/features/hashtag_timeline/index.js](https://github.com/imas/mastodon/blob/imastodon/app/javascript/mastodon/features/hashtag_timeline/index.js#L58)より、
/api/v1/streaming/hashtag/localには接続していないので、普通の利用者はlocalのみのほうを見ることはできないはず

**Comment by fvh-P** [comment]
とりあえず現状でPR出しました。何か変更漏れその他変更点がある場合はReviewでお願いします。

**Comment by fvh-P** [comment]
> 普通の利用者はlocalのみのほうを見ることはできないはず

カラム設定にトグルスイッチを追加して切り替えられるように試みています。
現状は外づらだけ出来ています(スイッチはおろか正規表現フィルタも動いていません)(なぜだ)
![local only](https://user-images.githubusercontent.com/8458066/29012948-27cca44c-7b7a-11e7-9c76-713386ed1a69.PNG)

変更は[こんな感じ](https://github.com/fvh-P/mastodon/commit/14fffb2450e1b6b6fc93c7debf0a86e68f4f173a)です(念のため本家のmasterを取ってきて変更しています。)
この先読み込むstreamを変更する処理を作るのに一苦労しそうです。

**Comment by lnanase** [comment]
> お気に入りタグ機能の自動入力連動で公開範囲をセットするようにする

こちらのタスクは担当させて下さい

**Comment by takayamaki** [comment]
このissueで立てた分のマイルストーンは全て実装したので閉じますー
