### ISSUE TITLE
画面が狭いときの編集時にお知らせが残る

### ISSUE THREAD

**Issue by deflis** [imas/mastodon#38]
問題の内容はあとで書く

**Comment by lnanase** [comment]
名刺を編集リンクとアイコンが移動する挙動となっているようですが、
お知らせ欄とかぶってしまっているので改善の余地がありますね。

![screenshot_20170811-014828](https://user-images.githubusercontent.com/11332152/29215461-06130fca-7ee6-11e7-8dba-48a2a94b7cfa.png)

**Comment by takayamaki** [comment]
マージしてデプロイしたのでクローズしますー
