### ISSUE TITLE
2021年10月頃から連合からimastodon.netの投稿が見えない

### ISSUE THREAD

**Issue by lonsagisawa** [imas/mastodon#438]
(私はすでにimastodon.netのLTLコミュニティに属していませんが、確実に管理者様にお伝えしたいためこちらをお借りしております)  
2021年10月2日頃から、imastodon.netの投稿が他のサーバーに届かなくなっており、一部のHTL運用の利用者が他のサーバーに疎開しなければいけない状況になっています。  
imastodon.netから他のサーバーの投稿は見えますので、意図的な鎖国ではなくサーバーになんらかの問題が生じているのではないかと思うのですが、如何でしょうか。

**Comment by rinsuki** [comment]
Let's Encrypt なインスタンスとは疎通できず、Cloudflare を通してるインスタンスとは通信できるので、DST Root X3 の失効回りの問題かも？(OpenSSL 1.0.2 系 + 古い ca-certificates で起こるというウワサ)

**Comment by rinsuki** [comment]
参考: https://www.walbrix.co.jp/article/openssl-102-letsencrypt-crisis.html

**Comment by takayamaki** [comment]
お疲れ様です、ご連絡ありがとうございます。

恥ずかしながら、仕事の多忙と見た目上あまりにも安定稼働しすぎていてその辺りの問題をすっかり見落としてしまっていました。
本件対応しましたのでそのうち流れるかと思います。

以上です、宜しくお願いします。

**Comment by lonsagisawa** [comment]
お忙しい中迅速なご対応をいただきありがとうございます。fedibird.comでトゥートが流れていることを確認いたしました。
