### ISSUE TITLE
日本語交じりのURLの一部が自動リンクの対象にならない

### ISSUE THREAD

**Issue by fvh-P** [imas/mastodon#57]
問題は既知ですが調査結果を共有しておきます。

good or bad | 入力内容 | 自動リンク処理結果
------- | ------------ | --------------------
👍 | https&#58;//www.yahoo.co.jp/ | [yahoo.co.jp/](https://www.yahoo.co.jp/)
👍 | http&#58;//日本語.jp/about | [日本語.jp/about](http://xn--wgv71a119e.jp/about)
👎 | http&#58;//dic.nicovideo.jp/a/アイドルマスター | [dic.nicovideo.jp/a/](http://dic.nicovideo.jp/a/)アイドルマスター

ホスト名に使われている日本語(おそらく非ASCII文字)はPunycodeで符号化されるらしく、有効です。
パス名に使われている日本語は無効になります。パス名を頭から読んでいって最初に非ASCII文字が出てきたところでURLとしての解釈が終わります。

Statusに投げられたプレーンテキストの処理には[twitter-textのExtractor](https://github.com/tootsuite/mastodon/blob/9ba7d526a0712afa073c6901bf2e69bae0dfab26/app/lib/formatter.rb#L66)が使われているため、twitter-textの仕様だろうと思われます。

![twitext](https://user-images.githubusercontent.com/8458066/29621221-1a1d2b76-885b-11e7-8f8a-31e730778be2.PNG)

しかし、面白いことに(？)LinkCardは正常に取得できています。
![linkcard](https://user-images.githubusercontent.com/8458066/29621497-ddaa867e-885b-11e7-90d3-15cf638420f3.PNG)

[FetchLinkCardService](https://github.com/tootsuite/mastodon/blob/1618b68bfa740ed655ac45d7d5f4f46fed6c8c62/app/services/fetch_link_card_service.rb#L4)によれば、LinkCardを生成する際のURL認識は正規表現で行われているようです。

**Comment by shin0O** [comment]
utf-8エンコード出来るものはLinkCard化出来そうだけど
ゲーム系wikiによくある非UTF-8なURLだとNGなのかな(未調査

**Comment by takayamaki** [comment]
本家にマージされてアイマストドンにも入ったので閉じますー
