### ISSUE TITLE
残りの画像もアイマス的なものに差し替えたい

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#68]
- [/app/javascript/images/mastodon_small.jpg](https://github.com/imas/mastodon/blob/imastodon/app/javascript/images/mastodon_small.jpg)
- [/app/javascript/images/elephant-friend-1.png](https://github.com/imas/mastodon/blob/imastodon/app/javascript/images/elephant-friend-1.png)

mastodon_small.jpgはFacebookやSlack、DiscordなどにURLを貼った際に表示されるサムネイル、
elephant-friend-1.pngは初回チュートリアルのモーダルに出るようです(下記参照
![image](https://user-images.githubusercontent.com/24884114/30074187-84084548-92ab-11e7-84ff-e8ebb9934e6b.png)

**Comment by takayamaki** [comment]
/app/javascript/images/mastodon_small.jpg のほうは
https://blog.sixapart.jp/2012-06/ogimage.html のような感じで扱われる模様

**Comment by lnanase** [comment]
#4913 でインスタンスのサムネイルが追加されたようです

**Comment by rinsuki** [comment]
https://github.com/imas/mastodon/commit/750db806f04197039c25c2d77e8361e52dff26bb でcloseしてしまっていいのではないでしょうか

**Comment by takayamaki** [comment]
🆗
