### ISSUE TITLE
シングルカラム状態において、未収載以下への返信の際に公開範囲が引き継がれない

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#71]
1. スマホ、またはブラウザの幅を狭くしてシングルカラム状態にします
1. 未収載以下のtootに対する返信ボタンを押します
1. 公開範囲が引き継がれません

一瞬引き継がれた後にpublicに再設定されている様子が稀に見えるので、
1. カラム遷移
1. 公開範囲引継ぎ
1. react-redux actionのlockTagCompose
1. ロックされているタグがないのでpublic
というような処理をたどっているような予感がします

**Comment by fvh-P** [comment]
自分の環境で試したところ、シングルカラムモードのときのみ以下のような動作が確認されました。

返信元ユーザのデフォルトの公開範囲と返信先tootの公開範囲を比べて、より**広い方**の公開範囲設定が適用される。
(本来は狭い方に合わせる動作であるはず？)

なのでデフォルトの公開範囲をUnlistedにしているときは、Privateなトゥートに返信を試みたときに同様の事象が再現します。

**Comment by takayamaki** [comment]
修正してデプロイしましたので閉じますー
