### ISSUE TITLE
お気に入りタグのロックを外した際に公開範囲がデフォルトに戻らない

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#87]
未収載以下の範囲のお気に入りタグをロックならびにアンロックした際、公開範囲がデフォルトの設定値に戻りません。

#71 と比べると公開範囲は狭いほうになるため緊急性は低いですが修正する必要はあります。

related #71, #75

**Comment by fvh-P** [comment]
公開範囲の異なる複数のお気に入りタグをロックしている際に、狭い公開範囲のものをすべてアンロックしても範囲設定が変わりません。

- [x] tag1 (public)
- [x] tag2 (unlisted)
のように公開範囲の異なる複数のお気に入りタグをロックした後、

- [x] tag1 (public)
- [ ] tag2 (unlisted)
とunlistedのものを解除しても公開範囲設定がpublicになりません。

これも公開範囲は狭いほうになるため緊急性は低いですが修正の必要があるかと思います。

**Comment by lnanase** [comment]
ご迷惑おかけして申し訳ありません。
少々、```reducers/compose.js``` を複雑化させてしまったと反省しています。

#86 の対応の時に修正しようと思います。
