### ISSUE TITLE
v1.4.1への追従

### ISSUE THREAD

**Issue by takayamaki** [imas/mastodon#9]
v1.4系列にて行われたWebpackの導入ならびにJavascriptの置き場所変更が
アイマストドン独自機能のcommitとコンフリクトしているためマージに苦戦している件

**Comment by lnanase** [comment]
v1.4.1タグのコミットからマージコミットを作成して、
こちらからプルリクエストを作成しようと思います。
本日の夜には対応する予定ですので、お手数ですがそれまでお待ち下さい。

**Comment by takayamaki** [comment]
すみません、ありがとうございます。

あと #8 のPRはどうしましょうか。
v1.4.1に上げるにあたってDBのマイグレーション=停止メンテが必要になるので使えると嬉しいのは事実なのですが、 #8 をマージしてからすぐにv1.4.1追従となると色々面倒くさくないかが心配でして。

**Comment by lnanase** [comment]
#8 をマージしてからv1.4.1マージでもこちらは構いません。
コンフリクトはどうあっても発生しますので、
#8 の機能が先に必要であればそちらを先に精査、マージして頂ければと思います。

よろしくお願い致します。

**Comment by takayamaki** [comment]
すみません、今まだ出先でしてテスト用ブランチ作ったところまでで動作確認出来てないです…
大阪公演までにはなんとかしたい

**Comment by takayamaki** [comment]
いずれにせよ、先に #8 マージしてメンテの告知少々してからの深夜メンテ（たぶん大阪公演後）で反映するつもりで今のところいますので、
その前提でご準備いただけますとお手間かけさせずに済むかと思います…

**Comment by takayamaki** [comment]
無事v1.4.1に移行できたのでcloseします
